language: python
matrix:
  include:
    - python: 3.3
      dist: trusty
      sudo: false
python:
  - "3.3"
# command to install dependencies
install:
  - pip install flake8
  - pip install pydocstyle
# command to run tests
script:
  - flake8 . --max-line-length=120
  - pydocstyle . --add-ignore=D202
